//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1Nyan.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S1Nyan.App.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string AboutPage {
            get {
                return ResourceManager.GetString("AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导航.
        /// </summary>
        public static string AppBarButtonNavigator {
            get {
                return ResourceManager.GetString("AppBarButtonNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一页.
        /// </summary>
        public static string AppBarButtonNextPage {
            get {
                return ResourceManager.GetString("AppBarButtonNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一页.
        /// </summary>
        public static string AppBarButtonPrePage {
            get {
                return ResourceManager.GetString("AppBarButtonPrePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string AppBarButtonRefresh {
            get {
                return ResourceManager.GetString("AppBarButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S1 Nyan.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载中.
        /// </summary>
        public static string AppLoading {
            get {
                return ResourceManager.GetString("AppLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大.
        /// </summary>
        public static string FontSizeLarge {
            get {
                return ResourceManager.GetString("FontSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中.
        /// </summary>
        public static string FontSizeMiddle {
            get {
                return ResourceManager.GetString("FontSizeMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小.
        /// </summary>
        public static string FontSizeSmall {
            get {
                return ResourceManager.GetString("FontSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        public static string NavigatorFirstPage {
            get {
                return ResourceManager.GetString("NavigatorFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 末页.
        /// </summary>
        public static string NavigatorLastPage {
            get {
                return ResourceManager.GetString("NavigatorLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页尾.
        /// </summary>
        public static string NavigatorPageBottom {
            get {
                return ResourceManager.GetString("NavigatorPageBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页首.
        /// </summary>
        public static string NavigatorPageTop {
            get {
                return ResourceManager.GetString("NavigatorPageTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh-CN.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string SettingPage {
            get {
                return ResourceManager.GetString("SettingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动旋转.
        /// </summary>
        public static string SettingPageAutoRotate {
            get {
                return ResourceManager.GetString("SettingPageAutoRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帖子文字大小.
        /// </summary>
        public static string SettingPageFontsize {
            get {
                return ResourceManager.GetString("SettingPageFontsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动显示图片.
        /// </summary>
        public static string SettingPageShowPics {
            get {
                return ResourceManager.GetString("SettingPageShowPics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        public static string SettingPageThemes {
            get {
                return ResourceManager.GetString("SettingPageThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总是.
        /// </summary>
        public static string ShowPicAlways {
            get {
                return ResourceManager.GetString("ShowPicAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从不.
        /// </summary>
        public static string ShowPicNone {
            get {
                return ResourceManager.GetString("ShowPicNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅Wifi.
        /// </summary>
        public static string ShowPicOnlyWifi {
            get {
                return ResourceManager.GetString("ShowPicOnlyWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S1.
        /// </summary>
        public static string ThemeS1 {
            get {
                return ResourceManager.GetString("ThemeS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统.
        /// </summary>
        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
    }
}
