//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1Nyan.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S1Nyan.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string AboutPage {
            get {
                return ResourceManager.GetString("AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户.
        /// </summary>
        public static string AccountPage {
            get {
                return ResourceManager.GetString("AccountPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换账户.
        /// </summary>
        public static string AccountPageChangeAccount {
            get {
                return ResourceManager.GetString("AccountPageChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访客.
        /// </summary>
        public static string AccountPageGuest {
            get {
                return ResourceManager.GetString("AccountPageGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登陆.
        /// </summary>
        public static string AccountPageLogin {
            get {
                return ResourceManager.GetString("AccountPageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在登陆.
        /// </summary>
        public static string AccountPageLoginLoading {
            get {
                return ResourceManager.GetString("AccountPageLoginLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出登陆.
        /// </summary>
        public static string AccountPageLogout {
            get {
                return ResourceManager.GetString("AccountPageLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string AccountPagePassword {
            get {
                return ResourceManager.GetString("AccountPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住密码.
        /// </summary>
        public static string AccountPageRememberPass {
            get {
                return ResourceManager.GetString("AccountPageRememberPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发帖显示签名.
        /// </summary>
        public static string AccountPageShowSignature {
            get {
                return ResourceManager.GetString("AccountPageShowSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册新账户.
        /// </summary>
        public static string AccountPageSignup {
            get {
                return ResourceManager.GetString("AccountPageSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        public static string AccountPageUsername {
            get {
                return ResourceManager.GetString("AccountPageUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导航.
        /// </summary>
        public static string AppBarButtonNavigator {
            get {
                return ResourceManager.GetString("AppBarButtonNavigator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一页.
        /// </summary>
        public static string AppBarButtonNextPage {
            get {
                return ResourceManager.GetString("AppBarButtonNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一页.
        /// </summary>
        public static string AppBarButtonPrePage {
            get {
                return ResourceManager.GetString("AppBarButtonPrePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string AppBarButtonRefresh {
            get {
                return ResourceManager.GetString("AppBarButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回复.
        /// </summary>
        public static string AppBarButtonReply {
            get {
                return ResourceManager.GetString("AppBarButtonReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S1 Nyan.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载中.
        /// </summary>
        public static string AppLoading {
            get {
                return ResourceManager.GetString("AppLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击此处登陆.
        /// </summary>
        public static string ErrorMsgClickToLogin {
            get {
                return ResourceManager.GetString("ErrorMsgClickToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接服务器失败.
        /// </summary>
        public static string ErrorMsgConnectServerFailed {
            get {
                return ResourceManager.GetString("ErrorMsgConnectServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据获取失败.
        /// </summary>
        public static string ErrorMsgGetDataFailed {
            get {
                return ResourceManager.GetString("ErrorMsgGetDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名/密码不能为空.
        /// </summary>
        public static string ErrorMsgNamePassEmpty {
            get {
                return ResourceManager.GetString("ErrorMsgNamePassEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有网络连接.
        /// </summary>
        public static string ErrorMsgNoNetwork {
            get {
                return ResourceManager.GetString("ErrorMsgNoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有可用的服务器.
        /// </summary>
        public static string ErrorMsgNoServerAvailable {
            get {
                return ResourceManager.GetString("ErrorMsgNoServerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回复成功.
        /// </summary>
        public static string ErrorMsgReplySuccess {
            get {
                return ResourceManager.GetString("ErrorMsgReplySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器更新成功.
        /// </summary>
        public static string ErrorMsgServerUpdateSuccess {
            get {
                return ResourceManager.GetString("ErrorMsgServerUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网站已关闭，请尝试登陆或等待服务器恢复.
        /// </summary>
        public static string ErrorMsgSiteClosed {
            get {
                return ResourceManager.GetString("ErrorMsgSiteClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务器不可用，尝试其他地址.
        /// </summary>
        public static string ErrorMsgTryCheckingOtherServers {
            get {
                return ResourceManager.GetString("ErrorMsgTryCheckingOtherServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误：.
        /// </summary>
        public static string ErrorMsgUnknown {
            get {
                return ResourceManager.GetString("ErrorMsgUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 意见反馈.
        /// </summary>
        public static string FeedBack {
            get {
                return ResourceManager.GetString("FeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s1nyanwp@gmail.com.
        /// </summary>
        public static string FeedBackEmail {
            get {
                return ResourceManager.GetString("FeedBackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S1Nyan 意见反馈.
        /// </summary>
        public static string FeedBackSubject {
            get {
                return ResourceManager.GetString("FeedBackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大.
        /// </summary>
        public static string FontSizeLarge {
            get {
                return ResourceManager.GetString("FontSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中.
        /// </summary>
        public static string FontSizeMiddle {
            get {
                return ResourceManager.GetString("FontSizeMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小.
        /// </summary>
        public static string FontSizeSmall {
            get {
                return ResourceManager.GetString("FontSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在浏览器中查看.
        /// </summary>
        public static string ImageShowInBrowser {
            get {
                return ResourceManager.GetString("ImageShowInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首页.
        /// </summary>
        public static string NavigatorFirstPage {
            get {
                return ResourceManager.GetString("NavigatorFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 末页.
        /// </summary>
        public static string NavigatorLastPage {
            get {
                return ResourceManager.GetString("NavigatorLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页尾.
        /// </summary>
        public static string NavigatorPageBottom {
            get {
                return ResourceManager.GetString("NavigatorPageBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页首.
        /// </summary>
        public static string NavigatorPageTop {
            get {
                return ResourceManager.GetString("NavigatorPageTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评分 &amp; 评论.
        /// </summary>
        public static string RateAndComment {
            get {
                return ResourceManager.GetString("RateAndComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh-CN.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string SettingPage {
            get {
                return ResourceManager.GetString("SettingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动旋转.
        /// </summary>
        public static string SettingPageAutoRotate {
            get {
                return ResourceManager.GetString("SettingPageAutoRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帖子文字大小.
        /// </summary>
        public static string SettingPageFontsize {
            get {
                return ResourceManager.GetString("SettingPageFontsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动显示图片.
        /// </summary>
        public static string SettingPageShowPics {
            get {
                return ResourceManager.GetString("SettingPageShowPics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        public static string SettingPageThemes {
            get {
                return ResourceManager.GetString("SettingPageThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 总是.
        /// </summary>
        public static string ShowPicAlways {
            get {
                return ResourceManager.GetString("ShowPicAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从不.
        /// </summary>
        public static string ShowPicNone {
            get {
                return ResourceManager.GetString("ShowPicNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅连接WiFi时.
        /// </summary>
        public static string ShowPicOnlyWifi {
            get {
                return ResourceManager.GetString("ShowPicOnlyWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不显示.
        /// </summary>
        public static string ShowSignatureNone {
            get {
                return ResourceManager.GetString("ShowSignatureNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S1主题.
        /// </summary>
        public static string ThemeS1 {
            get {
                return ResourceManager.GetString("ThemeS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统主题.
        /// </summary>
        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
    }
}
