// Json Mapping Automatically Generated By JsonToolkit Library for C#
// Diego Trinciarelli 2011
// To use this code you will need to reference Newtonsoft's Json Parser, downloadable from codeplex.
// http://json.codeplex.com/
// 

using System;
using Newtonsoft.Json;

namespace S1Parser
{
    public class DZForum
    {

        public string Version;
        public string Charset;
        public ForumVariables Variables;

        //Empty Constructor
        public DZForum()
        {
        }

        public string Serialize()
        {
            return JsonConvert.SerializeObject(this);
        }

        public static DZForum FromJson(string json)
        {
            return JsonConvert.DeserializeObject<DZForum>(json);
        }
    }

    public class Forum
    {

        public string Fid;
        public string Rules;
        public string Fup;
        public string Name;
        public int Threads;
        public int Posts;
        public string Autoclose;
        public string Password;

        //Empty Constructor
        public Forum()
        {
        }

    }

    public class Group
    {

        public string Groupid;
        public string Grouptitle;

        //Empty Constructor
        public Group()
        {
        }

    }

    public class ForumThreadlistItem : IThreadListItem
    {
        [JsonProperty("tid")]
        public string Id { get; set; }

        [JsonProperty("author")]
        public string Author { get; set; }

        [JsonProperty("subject")]
        public string Title { get; set; }

        [JsonProperty("lastposter")]
        public string LastPoster { get; set; }

        [JsonProperty("replies")]
        public string Subtle { get; set; }

        [JsonProperty("dbdateline"), JsonConverter(typeof (DateTimeConverter))]
        public DateTime AuthorDate { get; set; }

        [JsonProperty("dblastpost"), JsonConverter(typeof (DateTimeConverter))]
        public DateTime LastPostDate { get; set; }

        public string Authorid;
        public string Dateline;
        public string Digest;
        public string Lastpost;
        public string Readperm;
        public string Views;
        public string Attachment;

        //Empty Constructor
        public ForumThreadlistItem()
        {
        }

    }

    public class Sublist
    {

        public string Fid;
        public string Name;
        public string Threads;
        public string Posts;
        public string Todayposts;

        //Empty Constructor
        public Sublist()
        {
        }

    }

/*
    public class Threadtypes
    {

        public string Required;
        public string Listable;
        public string Prefix;
        public Types Types;
        public Icons Icons;
        public Moderators Moderators;

        //Empty Constructor
        public Threadtypes() { }

    }
*/

    public class ForumVariables : IThreadList
    {

        public string Cookiepre;
        public object Auth;
        public string Saltkey;
        public string Member_uid;
        public string Member_username;
        public string Groupid;
        public string Formhash;
        public string Ismoderator;
        public string Readaccess;
        public Forum Forum;
        public Group Group;
        public Sublist[] Sublist;
        public ForumThreadlistItem[] Forum_threadlist;

        [JsonProperty("tpp")]
        public int ItemsPerPage { get; set; }

        [JsonProperty("page")]
        public int CurrentPage { get; set; }

        public int TotalPage
        {
            get { return Forum.Threads/ItemsPerPage; }
        }

        public IThreadListItem[] ThreadList
        {
            get { return Forum_threadlist; }
        }

        //Empty Constructor
        public ForumVariables()
        {
        }
    }

}

//Json Mapping End

