// Json Mapping Automatically Generated By JsonToolkit Library for C#
// Diego Trinciarelli 2011
// To use this code you will need to reference Newtonsoft's Json Parser, downloadable from codeplex.
// http://json.codeplex.com/
// 

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace S1Parser
{
    public class DZHeader
    {
        public string Version;
        public string Charset;
        public JObject Variables;
        public Message Message;

        public string Serialize()
        {
            return JsonConvert.SerializeObject(this);
        }
        public static DZUser FromJson(string json)
        {
            return JsonConvert.DeserializeObject<DZUser>(json);
        }
    }

    public class Message
    {
        public string Messageval;
        public string Messagestr;

        //Empty Constructor
        public Message() { }
    }

}
//Json Mapping End
