// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace S1Parser
{

    public class ThreadType
    {

        [JsonProperty("required")]
        public string Required { get; set; }

        [JsonProperty("types")]
        public Dictionary<int, string> Types { get; set; }
    }

    public enum ForumTypes
    {
        Group,
        Forum,
        Sub
    }

    public class ForumItem
    {

        [JsonProperty("fid")]
        public string Fid { get; set; }

        [JsonProperty("type")]
        public ForumTypes Type { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("fup")]
        public string Fup { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("threadtypes")]
        public ThreadType Threadtypes { get; set; }

        [JsonProperty("postperm")]
        public string Postperm { get; set; }
    }

    public class ForumList : UserVariables
    {
        [JsonProperty("forums")]
        public ForumItem[] Forums { get; set; }
    }

}
