// Json Mapping Automatically Generated By JsonToolkit Library for C#
// Diego Trinciarelli 2011
// To use this code you will need to reference Newtonsoft's Json Parser, downloadable from codeplex.
// http://json.codeplex.com/
// 
using System;
using Newtonsoft.Json;

namespace S1Parser
{

    public class DZUser
    {
        public string Version;
        public string Charset;
        public UserVariables Variables;
        public Message Message;

        //Empty Constructor
        public DZUser() { }

        public string Serialize()
        {
            return JsonConvert.SerializeObject(this);
        }
        public static DZUser FromJson(string json)
        {
            return JsonConvert.DeserializeObject<DZUser>(json);
        }
    }

    public class UserVariables
    {
        public string Cookiepre;
        public string Auth;
        public string Saltkey;
        public string Member_uid;
        public string Member_username;
        public string Groupid;
        public string Formhash;
        public string Ismoderator;
        public string Readaccess;
        //[JsonProperty("member_uid")]
        //public string MemberUid { get; set; }

        //[JsonProperty("member_username")]
        //public string MemberUsername { get; set; }

        //Empty Constructor
        public UserVariables() { }

    }

}
//Json Mapping End
