// Json Mapping Automatically Generated By JsonToolkit Library for C#
// Diego Trinciarelli 2011
// To use this code you will need to reference Newtonsoft's Json Parser, downloadable from codeplex.
// http://json.codeplex.com/
// 
using System;
using Newtonsoft.Json;

namespace S1Parser
{
    public class DZThread
    {

        public string Version;
        public string Charset;
        public ThreadVariables Variables;

        //Empty Constructor
        public DZThread() { }

        public string Serialize()
        {
            return JsonConvert.SerializeObject(this);
        }
        public static DZThread FromJson(string json)
        {
            return JsonConvert.DeserializeObject<DZThread>(json);
        }
    }

    public class Thread
    {

        public string Tid;
        public string Fid;
        public string Posttableid;
        public string Typeid;
        public string Sortid;
        public string Readperm;
        public string Price;
        public string Author;
        public string Authorid;
        public string Subject;
        public string Dateline;
        public string Lastpost;
        public string Lastposter;
        public string Views;
        public string Replies;
        public string Displayorder;
        public string Highlight;
        public string Digest;
        public string Rate;
        public string Special;
        public string Attachment;
        public string Moderated;
        public string Closed;
        public string Stickreply;
        public string Recommends;
        public string Recommend_add;
        public string Recommend_sub;
        public string Heats;
        public string Status;
        public string Isgroup;
        public string Favtimes;
        public string Sharetimes;
        public string Stamp;
        public string Icon;
        public string Pushedaid;
        public string Cover;
        public string Replycredit;
        public string Relatebytag;
        public int Maxposition;
        public string Bgcolor;
        public string Comments;
        public string Threadtable;
        public string Threadtableid;
        public string Posttable;
        public string Allreplies;
        public string Is_archived;
        public string Archiveid;
        public string Subjectenc;
        public string Short_subject;
        public string Recommendlevel;
        public string Heatlevel;
        public string Relay;

        //Empty Constructor
        public Thread() { }

    }

    public class Postlist
    {

        public string Pid;
        public string Tid;
        public string First;
        public string Author;
        public string Authorid;
        public string Dateline;
        public string Message;
        public string Anonymous;
        public string Attachment;
        public string Status;
        public string Username;
        public string Adminid;
        public string Groupid;
        public string Memberstatus;
        public int Number;
        public string Dbdateline;

        //Empty Constructor
        public Postlist() { }

    }

    public class Setting_rewriterule
    {

        public string Portal_topic;
        public string Portal_article;
        public string Forum_forumdisplay;
        public string Forum_viewthread;
        public string Group_group;
        public string Home_space;
        public string Home_blog;
        public string Forum_archiver;
        public string Plugin;

        //Empty Constructor
        public Setting_rewriterule() { }

    }

    public class ThreadVariables
    {

        public string Cookiepre;
        public object Auth;
        public string Saltkey;
        public string Member_uid;
        public string Member_username;
        public string Groupid;
        public string Formhash;
        public string Ismoderator;
        public string Readaccess;
        public Thread Thread;
        public string Fid;
        public Postlist[] Postlist;
        public string[] Imagelist;
        public string Ppp;
        public Setting_rewriterule Setting_rewriterule;
        public string[] Setting_rewritestatus;
        public string Forum_threadpay;
        public string[] Cache_custominfo_postno;
        public Forum Forum;

        //Empty Constructor
        public ThreadVariables() { }

    }

}
//Json Mapping End
